name: Destroy AWS Infrastructure with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.8.1'  # Specify your desired Terraform version

      # Step 3: Configure AWS credentials (GitHub Secrets)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Terraform Plan (optional, to verify what will be destroyed)
      - name: Terraform Plan
        run: terraform plan -destroy

      # Step 6: Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve

